### ISSUE TITLE
用于v-model的ref变量被转化为了计算属性

### ISSUE THREAD

**Issue by AprildreamMI** [lim-f/create-lim#1]
![image](https://github.com/user-attachments/assets/2bd159f4-83a3-484e-b896-8e2bc211989a)

**Comment by theajack** [comment]
感谢指出，下个版本修复 @AprildreamMI

**Comment by theajack** [comment]
@AprildreamMI 此问题在vue-lim@0.0.9中 已修复，playground也已更新
